### PR TITLE
4.0.0 Release

### PR DESCRIPTION
**Pull request by EEParker**
All changes from 3.7.0 to 4.0.0.

- [ ] Tag this merge request with `4.0.0` once merged to master

### CODE REVIEW

**Comment by VictorioBerra** [comment]
Great job @EEParker!!!

**Comment by EEParker** [comment]
FYI, I removed the master branch for now. To make a release simply tag a commit on the dev branch.

The automation works better with in line commits, the squash commit to master skipped the change log.

**Comment by VictorioBerra** [comment]
Got it. Any reason why to remove the master branch?

**Comment by EEParker** [comment]
It wasn't serving any purpose and might make the release process more confusing. I also don't have access to change branch settings, so just working off dev and feature branches seems best for now.

**Pull request merged**
