### PR TITLE
Fix for missing TraceId and SpanId

### PR DESCRIPTION
**Pull request by EEParker**
This PR adds a reproduction for #195 to the sample project.

### CODE REVIEW

**Comment by EEParker** [comment]
image
Sample app reproduction and fix success.

**Comment by EEParker** [comment]
Implement changes from https://github.com/serilog/serilog/pull/1955

**Comment by VictorioBerra** [comment]
@EEParker overwriting the current TraceIdentifier won't break anything right? Not an expert on that but that's for the entire request right? Would that affect any other middleware?

**Comment by EEParker** [comment]
Are you referring to the sample app? That is to add a fake traceid since it isn't running aspnetcore. The actual sink is just adding the missing fields from the upstream generic json sink.

**Comment by VictorioBerra** [comment]
I was looking at this on my phone and didn't see what app the file was in, looks good!

**Pull request merged**
