### PR TITLE
Vs2017 tooling

### PR DESCRIPTION
**Pull request by merbla**
Addresses #47

### CODE REVIEW

**Comment by nblumhardt** [comment]
Hrmm, looks like this published a non-dev package (2.2.0). Looks like we're missing `--version-suffix` in the build script. :-(

**Comment by merbla** [comment]
:nauseated_face: oops.  Will track down the diff. 

I have deleted the package to be sure.

**Comment by merbla** [comment]
@nblumhardt what do you get for `dotnet --info`

```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```
The package is not getting the suffix with the following...

```
dotnet pack -c Release --include-symbols -o ..\..\artifacts --version-suffix=blah --no-build
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  Successfully created package 'C:\Code\serilog-sinks-splunk\artifacts\Serilog.Sinks.Splunk.2.2.0.nupkg'.
  Successfully created package 'C:\Code\serilog-sinks-splunk\artifacts\Serilog.Sinks.Splunk.2.2.0.symbols.nupkg'.
```

**Comment by merbla** [comment]
@nblumhardt I think I have it over at #49

**Comment by nblumhardt** [comment]
👍 - sorry to have dropped off the radar yesterday, had time-away-from-keyboard. Looks like it's sorted? Yell if you need a hand with anything.

**Pull request merged**
